spin_manifest_version = 2

[application]
name = "ai-live"
version = "0.1.0"
authors = ["Thorsten Hans <thorsten.hans@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "ai-live"

[component.ai-live]
source = "target/wasm32-wasi/release/ai_live.wasm"
allowed_outbound_hosts = []
ai_models = ["llama2-chat"]
key_value_stores = ["default"]
files = ["README.md"]

[component.ai-live.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
